kong-database:
 image: cassandra:2.2
 ports:
   - "9042:9042"
 container_name: kong-database


abdulkong2:
 image: abdulkong
 ports:
   - "8000:8000"
   - "8443:8443"
   - "8001:8001"
   - "7946:7946"
   - "7946:7946/udp"
 environment:
   - KONG_DATABASE=cassandra
   - KONG_CASSANDRA_CONTACT_POINTS=kong-database
 links:
   - kong-database
   - abdulphpserver
   - mysqldatabase
 container_name: kong

abdulphpserver:
 image: abdulphpserver
 ports:
   - "8020:8020"
 volumes:
   - /home/samuel/Codes/my.service:/web
 container_name: abdulphpserver
 links:
   - mysqldatabase

mysqldatabase:
 image: mysql
 ports:
   - "3306:3306"
 environment:
   - MYSQL_ROOT_PASSWORD=test
 container_name: mysqldatabase
 volumes:
   - /home/samuel/Codes/kongdocker/mysql/my.cnf:/etc/mysql/conf.d
#   - /home/abdul/Kong/kongdocker/mysql:/etc/mysql/conf.d
# ignore this line samuel, was just my environment
